name: Go coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Build
        run: go install

      - name: Test
        run: |
          go test -v -cover ./... -coverprofile coverage.out -coverpkg ./...

      - name: Report Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: "*.out"
